### PR TITLE
docs: endpoints readme

### PR DESCRIPTION
**Pull request by victorforissier**

### CODE REVIEW

**Comment by lowczarc** [comment]
I suppose (and hope) it's generated with GPT/Claude.

It's basically all garbage. I didn't check everything in detail but by looking at it 2s:
The authentification is done with `X-Access-Token`, not with authorization
Generate uses the task parameter, not input.
STT needs to be send a file path of a file previously uploaded on supabase and not a base64 of the file.
The error handling part is basically useless since it just explain the HTTP error status and doesn't give any of the error we are actually sending.

I don't think it's worth to add doc if we're deprecating it anyway

**Review by lowczarc — CHANGES_REQUESTED** [review]
No doc is better than fake doc

**Comment by victorforissier** [comment]
Yeah it's Sonnet 3.5 I thought it'd just take the endpoint ref and didn't double check. 
All the doc archive is in the SDK repo now we can forget that.

**Comment by lowczarc** [comment]
I'm closing then

**Pull request closed without merging**
